//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunFramework.DataAccess.Model.Service
{
    using SunFramework.Interface.Model;
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceResponse
    {
        public int ServiceResponseId { get; set; }
        public int ServiceId { get; set; }
        public Nullable<int> ServiceRequestId { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public string ResponseStatusCode { get; set; }
        public string ResponseData { get; set; }
    
        public virtual IServiceModel Service { get; set; }
        public virtual IServiceRequestModel ServiceRequest { get; set; }
    }
}
