//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunFramework.DataAccess.Model.Service
{
    using SunFramework.Interface.Model;
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Service1 = new HashSet<IServiceModel>();
            this.ServiceRequests = new HashSet<IServiceRequestModel>();
            this.ServiceResponses = new HashSet<IServiceResponseModel>();
        }
    
        public int ServiceId { get; set; }
        public int ServiceStatusId { get; set; }
        public string HostName { get; set; }
        public int PortNo { get; set; }
        public Nullable<int> BackupServiceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IServiceModel> Service1 { get; set; }
        public virtual IServiceModel Service2 { get; set; }
        public virtual IServiceStatusModel ServiceStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IServiceRequestModel> ServiceRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IServiceResponseModel> ServiceResponses { get; set; }
    }
}
