//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunFramework.DataAccess.Model.Identity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public System.Guid UserId { get; set; }
        public System.DateTimeOffset LoginDate { get; set; }
    }
}
