//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunFramework.EntityFramework.Model.Identity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserIdentity
    {
        public Nullable<System.Guid> UserId { get; set; }
        public string Value { get; set; }
        public int IdentityTypeId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual IdentityType IdentityType { get; set; }
        public virtual User User { get; set; }
    }
}
